config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  resources :links, only: [:create, :show]
  get ':action' => 'welcome#:action'
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessor :encode, :decode

  LIBRARY = Array('a'..'z') + Array('A'..'Z') + Array('0'..'9')
  TRANSCRIPTION_ERRORS = {'0' => 'O', '1' => 'l'}
  OFF_LIMITS = ['foo', 'fop', 'bar', 'f']
  SPECIAL_CHARACTER = '$'

  def self.transcribe(string)
    string.gsub(/./){|n|TRANSCRIPTION_ERRORS[n] || n}
  end

  @@alphabet = self.transcribe(LIBRARY.join('')).split('').uniq

  def get_short_url(i=nil)
    i ||= id
    return @@alphabet[0] if i == 0
    s = ''
    base = @@alphabet.length
    while i > 0
      s << @@alphabet[i.modulo(base)]
      i /= base
    end
    s.reverse
  end

  def encode
    short = get_short_url
    disp = 0
    while OFF_LIMITS.include?(short.gsub(SPECIAL_CHARACTER,''))
      disp += 1
      short = get_short_url(id + disp) + (SPECIAL_CHARACTER * disp)
    end
    self.short_url = short
    save
  end

  def self.decode(string)
    Link.find_by_short_url(Link.transcribe(string)).try(&:long_url)
  end

  def self.decode_id(string)
    i = 0
    base = @@alphabet.length
    string = Link.transcribe(string)
    string.each_char { |c| c == Link::SPECIAL_CHARACTER ? (i-=1) : i = i * base + @@alphabet.index(c) }
    i
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  require "net/http"

  def create
    if !link_params[:long_url].blank? && link_params[:encode]
      @link = Link.find_by_long_url(link_params['long_url']) || Link.create(link_params)
      @link.encode
      @short_url = [request.protocol + request.host_with_port, @link.short_url].join('/')
    elsif !link_params[:short_url].blank? && link_params[:decode]
      path = URI.parse(link_params[:short_url]).path.gsub("/","")
      @long_url = Link.decode(path)
      @flash = 'Short link not found' if @long_url.blank?
    end
  end

  private

  def link_params
    params.require(:link).permit([:long_url, :short_url, :encode, :decode])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @reverse = params[:reverse]
  end

  def action_missing(action_name)
    link = Link.find_by_short_url(action_name).long_url
    link.increment(:count, by = 1)
    link = "http://" + link if !link.include?("http")
    redirect_to link, status: 302
  rescue NoMethodError
    flash[:alert] = "This shortened link does not exist"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def append_icon(text, icon)
    (text + "<i class='fa fa-#{icon}' style='padding-left:10px;'></i>").html_safe
  end
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %h3= link_to 'Short.it', root_path, class: 'navbar-brand'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Shortit'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Shortit'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main", :id => "main_container"}
      = render 'layouts/messages'
      = yield

app/views/links/create.js.erb
<% if @short_url %>
  $("#link_short_url").val("<%= @short_url %>")
<% elsif @long_url %>
  $("#link_long_url").val("<%= @long_url %>")
<% end %>
$("#flash").html("<%= @flash%>")
<% if !@flash.blank? %>
  $("#flash").css("display","block")
<% else %>  
  $("#flash").css("display","none")
<% end %>

app/views/welcome/index.html.haml
#flash.alert.alert-danger

%h3 Welcome

%p The following is a link shortening program.  Enter a link and click the bullseye.  Click the copy button to copy the short url.  To see the source code click #{link_to append_icon("here","bitbucket"), "https://bitbucket.org/kprifogle/shortit/src/8572e44fb6d34b48d9441b97d7c23b7468a0ea8e?at=master", :target => "_blank"}.
%p.hint Note that you can include the protocal in the link if you want.

.indent
  = simple_form_for(:link, :url => links_path, :remote => true, :html => {:id => "urls", :class => "form-horizontal"}) do |f|
    -field = @reverse ? :short_url : :long_url
    -type = @reverse ? :decode : :encode
    =f.input field, :wrapper => :append do
      = f.input_field field, :class => "form-control"
      %button#submit_button.btn.appended_button
        %i.fa.fa-bullseye
    #switch
      = link_to append_icon("Switch","arrows-v"), root_path(!@reverse ? {:reverse => true} : {})
    -field = @reverse ? :long_url : :short_url
    =f.input field, :wrapper => :append do
      = f.input_field field, :class => "form-control"
      %button#clipboard_button.btn.appended_button{"data-clipboard-target" => "short_url", "data-clipboard-text" => "Default clipboard text from attribute", :title => "Click to copy"}
        %i.fa.fa-copy
    = f.hidden_field (@reverse ? :decode : :encode), :value => true
#description_well.well
  %h5 Description of the task

  %p Create a Rails web service that has the following behaviors:

  %ul
    %li Given a long URL, it will provide a short URL
    %li Given a short URL that it generated, it will provide the corresponding long URL
    %li Short URLs are likely to be transcribed by hand, so they should accommodate common transcription ambiguities. O and 0 should be treated identically, for example.
    %li On the other hand, transcription errors should ideally not result in false results. The short URLspace should be sparse, specifically having the property that no two short URLs should differ by only one character.  (To address this I reduced the alphabet to treat as the same transcription errors, try "bOO" and "b00", "link" and "1ink")
    %li Short URLs must not contain any string in a list of inappropriate words. The list should be stubbed as "foo" and "bar" while legal trawls 4chan and compiles a master list of terms calculated to give offense.